### ISSUE TITLE
Add stable redis bloom filters

### ISSUE THREAD

**Issue by Crystark** [Baqend/Orestes-Bloomfilter#17]
Hi,

These implementations of bloom filter are really nice, especially the Redis-backed bloom filter !

I read about  [stable bloom filters](http://en.wikipedia.org/wiki/Bloom_filter#Stable_Bloom_filters) and found some infos [here](http://books.google.fr/books?id=DFnOAwAAQBAJ&lpg=PA347&ots=CTwSyjne1o&dq=The%20update%20step%20first%20calls%20this%20decrement&pg=PA347#v=onepage&q=The%20update%20step%20first%20calls%20this%20decrement&f=false) (yeah i know, it's a bit blurry and the previous page is missing). It seems to be able to handle infinite values using an aging system. One could then configure a max age so that the size of the bloom filter stays stable.

Do you think it's something you could implement easily based on the Redis Counting Bloom Filters ?
Thanks!

**Comment by DivineTraube** [comment]
Hi,

thanks for the suggestion. I looked into stable bloom filters when implementing the library and decided not include them. The problem is that they are unsuitable to many applications: they do not only allow false positives but false negatives too! If you would like to submit a pull request for this feature, we would of course be happy to include it.

In order to implement this for Redis, you would have to write very little code. You could just imitate the RedisCountingBloomFilter implementation and would have to change the add() and contains() method (no remove method). Instead of increasing the counter in the corresponding Redis hash you would set the hash positions to MAX_COUNTER and choose d (new configuration parameter) random cells that get decremented. You could also just drop the materialization of the normal Bloom filter. All in all, you would probably have to write 20-50 lines of code + tests. A good description besides the original paper is this summary: http://matthias.vallentin.net/blog/2011/06/a-garden-variety-of-bloom-filters/

Let my know if you have any questions!

Best regards,
Felix
